theme: jekyll-theme-so-simple
# remote_theme: mpdeimos/so-simple-theme@downstream
locale: en-US
title: "martinpoehlmann.com"
description: "Martin Pöhlmann"
copyright: |
  © 2023 martinpoehlmann.com
  • [About](/about/) 
  • [Impressum](/impressum/)
baseurl: / # the subpath of your site, e.g. "/blog"
url: https://martinpoehlmann.com # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: 150
#mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Condiment"
    weights: "400"
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "Source Code Pro"
    weights: "400,700"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: "mpdeimos"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:collection/:categories/:year-:month-:day-:title/

collections:
  works:
    output: true

markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: /posts/page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/posts/categories/#"
tag_archive_path: "/posts/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .github/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      share: false
      comments: false
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      comments: true
  - scope:
      path: "_works"
      type: works
    values:
      layout: page
      share: false
      comments: false

# Site Author
author: mpdeimos

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss
  - title: Twitter
    url: https://twitter.com/mpdeimos
    icon: fab fa-twitter
  - title: GitHub
    url: https://github.com/mpdeimos
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/martinpoehlmann/
    icon: fab fa-linkedin-in 
  - title: Strava
    url: https://www.strava.com/athletes/181593
    icon: fab fa-strava
  - title: Last.FM
    url: https://www.last.fm/user/mpdeimos
    icon: fab fa-lastfm

icon: fas fa-link-square
skin: "/assets/css/skin.css"